// F-137 / F-166 audit action → friendly Korean label (unknown actions fall back to a prefix label, then the raw code).
const EXACT: Record<string, string> = {
  "export.created": "내보내기 파일 생성",
  "export.downloaded": "내보내기 파일 다운로드",
  "export.google_sheets": "Google Sheets로 내보내기",
  "export.google_drive": "Google Drive에 저장",
  "privacy.export": "내 데이터 받기",
  "privacy.delete_requested": "계정 삭제 요청",
  "consent.updated": "동의 설정 변경",
  "auth.device_revoked": "기기 로그아웃",
  "auth.passkey_registered": "패스키 등록",
  "auth.passkey_deleted": "패스키 삭제",
  "device_key.registered": "기기 키 등록",
  "contact.created": "연락처 추가",
  "contact.updated": "연락처 수정",
  "contact.deleted": "연락처 삭제",
  "contact.merged": "연락처 병합",
  "contact.merge_undone": "연락처 병합 취소",
  "capture.created": "명함 스캔",
  "capture.image_stored": "명함 이미지 저장",
  "capture.image_deleted": "명함 이미지 삭제",
  "exchange.session_created": "교환 링크 생성",
  "exchange.revoked": "교환 링크 폐기",
  "exchange.offline_synced": "오프라인 교환 동기화",
  "exchange.proximity_exchanged": "근거리 교환",
  "exchange.rendezvous_confirmed": "만남 교환 확인",
  "guest.claimed": "카드 소유 등록",
  "integration.google.sync_requested": "Google 연락처 동기화 요청",
  "integration.google.disconnected": "Google 연결 해제",
  "integration.job.retried": "동기화 작업 재시도",
  "integration.mapping.saved": "CRM 필드 매핑 저장",
  "message.draft_created": "메일 초안 작성",
  "message.sent": "메일 발송",
  "message.send_failed": "메일 발송 실패",
  "message.gmail_draft_saved": "Gmail 초안 저장",
  "calendar.candidate.approved": "일정 승인",
  "calendar.candidate.declined": "일정 거절",
  "calendar.candidate.cancelled": "일정 취소",
  "calendar.booking_page.created": "예약 페이지 생성",
  "meeting.recording_consent": "녹음 동의 기록",
  "meeting.recording_started": "녹음 시작",
  "meeting.recording_finalized": "녹음 완료",
  "push.subscribed": "이 기기 알림 켜기",
  "push.unsubscribed": "이 기기 알림 끄기",
  "webhook.created": "웹훅 추가",
  "webhook.deleted": "웹훅 삭제",
  "webhook.secret_rotated": "웹훅 비밀키 교체",
  "org.created": "조직 생성",
  "org.deleted": "조직 삭제",
  "org.member_joined": "조직 합류",
  "org.member_departed": "조직 탈퇴",
  "org.member_prefs": "내 멤버십 설정 변경",
  "org.contacts_shared": "팀에 연락처 공유",
  "org.contact_unshared": "팀 공유 해제",
  "org.team_note_added": "팀 메모 추가",
  "org.team_note_deleted": "팀 메모 삭제",
  "billing.checkout_started": "결제 시작",
  "template.deleted": "템플릿 삭제",
  "assistant.prefs_updated": "어시스턴트 설정 변경",
};

const PREFIX: [string, string][] = [
  ["integration.conflict.", "동기화 충돌 처리"],
  ["integration.", "연동 작업"],
  ["export.", "내보내기"],
  ["org.", "조직 설정 변경"],
  ["profile.", "카드 수정"],
  ["calendar.", "일정 작업"],
  ["event.", "행사 작업"],
  ["intro.", "소개 작업"],
  ["followup.", "후속 작업"],
  ["sso.", "SSO 설정"],
  ["apikey.", "API 키 작업"],
  ["wallet.", "지갑 카드 발급"],
  ["nfc_tag.", "NFC 태그 작업"],
];

export function auditLabel(action: string): string {
  return EXACT[action] ?? PREFIX.find(([p]) => action.startsWith(p))?.[1] ?? action;
}
